model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY

  - model_name: llava
    litellm_params:
      model: ollama/llava:latest
      api_base: http://localhost:11434

  - model_name: gemma3-4b
    litellm_params:
      model: ollama/gemma3:4b
      api_base: http://localhost:11434
    model_info:
      stream: true

  - model_name: qwen2.5vl
    litellm_params:
      model: ollama/qwen2.5vl:latest
      api_base: http://localhost:11434

  - model_name: minicpm-v:8b
    litellm_params:
      model: ollama/minicpm-v:8b
      api_base: http://localhost:11434

litellm_settings:
  drop_params: true
  # success_callback: ["mlflow"]
  # failure_callback: ["mlflow"]
  callbacks: ..custom_callbacks.proxy_handler_instance